name: Run tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      testSuite:
        description: 'Optional test suite (e.g. smoke, full)'
        required: false
        default: ''

jobs:
  run-wdio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}  

      - name: Debug inputs
        run: |
          echo "github.event.inputs.testSuite: '${{ github.event.inputs.testSuite }}'"
          echo "inputs via tojson: ${{ toJSON(github.event.inputs) }}"

      - name: Determine which suite to run
        run: |
          if [ "$GITHUB_EVENT_NAME" = "push" ]; then
            echo "TEST_SUITE=regression" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.testSuite }}" != "" ]; then
            echo "TEST_SUITE=${{ github.event.inputs.testSuite }}" >> $GITHUB_ENV
          else
            echo "TEST_SUITE=" >> $GITHUB_ENV
          fi    

      - name: Debug inputs
        run: |
          echo "Event name: $GITHUB_EVENT_NAME"
          echo "Chosen suite: $TEST_SUITE"

      - name: Run WebdriverIO tests
        run: |
          if [ -n "$TEST_SUITE" ]; then
            echo "Running suite: $TEST_SUITE"
            npm run wdio -- --suite "$TEST_SUITE"
          else
            echo "Running default suite"
            npm run wdio
          fi