name: Run tests

on:
  workflow_dispatch:
    inputs:
      testSuite:
        description: 'Optional test suite (e.g. smoke, full)'
        required: false
        default: ''

jobs:
  run-wdio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Run WebdriverIO tests
        run: |
          if [ "${{ github.event.inputs.testSuite }}" != "" ]; then
            npm run wdio -- --suite ${{ github.event.inputs.testSuite }}
          else
            npm run wdio
          fi